/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-index.ts' */
import { recommended } from './configs/recommended';
import noHollowCatch from './rules/no-hollow-catch'

export const configs = {
    recommended
};

export const rules = {
    'no-hollow-catch': noHollowCatch
};
